# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMconnection'
    subscriptionId: '32e4e8a6-a0e9-4020-b6a6-367c8f47c884'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Study'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Simran287/ARMtemplates/refs/heads/main/storageaccountdeploy.json'
    deploymentMode: 'Incremental'
    deploymentName: 'deploySApipeline'